### ISSUE TITLE
[parser] add Eol check logic in the end of the line

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/koa#138]
**Where**
parse.go

**Bug detail**
We should check the end of line! 

**Fix plan**
Add following line `expectNext(buf,Eol)`

**Comment by joomanzi** [comment]
this issue might handle in lexer

In golang, compiler automatically add semicolon at end of statement.
and by semicolon, easily check whether  token stream is at end of statement or not
we can follow this rule

check this out:
https://golang.org/ref/spec#Semicolons
https://golang.org/doc/effective_go.html#semicolons
https://medium.com/golangspec/automatic-semicolon-insertion-in-go-1990338f2649

**Comment by joomanzi** [comment]
referece go_sdk src/go/scanner insertSemi

**Comment by zeroFruit** [comment]
Really helpful!

**Comment by zeroFruit** [comment]
on it! @zeroFruit
