### ISSUE TITLE
[doc] Fix doc for parser!

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/koa#174]
**Subject**
parser

**Detail**
Fixed some doc contents for parser about something changed!

**Comment by joomanzi** [comment]
+)) well, seems like there don't need any difference in doc. but in readme.md

**Comment by hihiboss** [comment]
@joomanzi 
Oh, lexer does not need it, but parser need it!!
program -> contract / contract has functions and function has statements, not proagram has statements!

**Comment by zeroFruit** [comment]
on it

**Comment by zeroFruit** [comment]
I will update docs when I finish to write about parser in english in medium!
