### ISSUE TITLE
[vm] add `and` `or` `jump` `dup`  `swap` opcode

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/koa#254]
**Detail**
need to implement new opcode

- [ ] and
- [ ] or
- [ ] jump
- [ ] dup
- [ ] swap

**Comment by junbeomlee** [comment]
assigned to @hea9549

**Comment by hea9549** [comment]
i think there is two option to make dup operation.
one option is that pop 2 element in stack. First one means duplicate times and last one means data to duplicate.
or second option is that pop only 1 element to duplicate. pop and duplicate just one time.

ethereum have many dup opcode (dup1, dup2 , dup3 .... dup 16)

which method is better on your thought?

**Comment by junbeomlee** [comment]
i think only dup1 is enough for v0.1.0 koa

**Comment by AgwaB** [comment]
ethereum use dup opcode when they use variable. But we store variables in the memory! so I think now it is enough to implement dup1 opcode!
