### ISSUE TITLE
[vm] Implement opcode's instruction and testcase

### ISSUE THREAD

**Issue by AgwaB** [DE-labtory/koa#61]
**Subject**
opcode.go, vm.go

**Detail**
In vm.go, opcode's instruction should be implemented.

ex) `Add`, `Push`, `Pop`, `Mul`, `Sub`, `Div`, `Mod` ...

**Comment by kwongiho** [comment]
Assigned to me

**Comment by AgwaB** [comment]
@KwonGiho ok! but after merged #72, i'll implement basic opcode `Add`, `Push` to show example!
