### ISSUE TITLE
[lex] Modify defaultStateFn

### ISSUE THREAD

**Issue by joomanzi** [DE-labtory/koa#97]
**Subject**
[lex] Modify defaultStateFn
// TODO: LTE, GTE, spaceStateFn, numberStateFn, identifierStateFn case

**Detail**
- [ ] LTE
- [ ] GTE
- [ ] spaceStateFn
- [ ] numberStateFn
- [ ] identifierStateFn

**Comment by junbeomlee** [comment]
assigned to @junbeomlee
