### ISSUE TITLE
[lex] Implement CLI test tool

### ISSUE THREAD

**Issue by joomanzi** [DE-labtory/koa#98]
**Subject**
[lex] Implement CLI test tool

**Detail**
Implement CLI test tool

ex) input : " int number = 10"
     output :
 {Type : IntType Val : int},
{Type : Ident Val : number},
{Type : Equal Val : =},
{Type : Int Val : 10},

**Comment by zeroFruit** [comment]
it is a suggestion. if cli is for testing how about setting cli mode like:
* lex mode: test lexing
* parse mode: test lexing + parsing
* compile mode: test lexing + parsing + compiling
...
?

**Comment by joomanzi** [comment]
good idea!
From now, starting at lex but it could be extended

**Comment by zeroFruit** [comment]
ok! please consider the options I told when you code the CLI

**Comment by junbeomlee** [comment]
assigned to @junbeomlee
